### ISSUE TITLE
Assignment list is randomly ordered

### ISSUE THREAD

**Issue by derrell** [NatTuck/bottlenose-classic#10]
The list of assignments under a Chapter changes order randomly, as assignments are edited or added. The order should be consistent. I recommend that it be either inversely by due date (most recent at the top -- my preference), or by due date.

**Comment by derrell** [comment]
The order of assignments changes similarly (randomly) in the Student Status Report.

**Comment by NatTuck** [comment]
Chapters and assignments are now displayed in alphabetical order. You can now number them to enforce an explicit ordering.
