### ISSUE TITLE
BN is sending auth links with HTTP (not HTTPS)

### ISSUE THREAD

**Issue by fgmart-zz** [NatTuck/bottlenose-classic#102]
If you do an auth link reset, the URL you get sent starts with http.

It needs to start with HTTPS.

Example below.

```
Date: Sun, 11 Jan 2015 15:17:15 -0500
From: Bottlenose <noreply@cs.uml.edu>
To: fgmartin13@gmail.com
Message-ID: <54b2da4bedbe_1fe8cd0aa050653@grader.mail>
Subject: Course authentication link
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Hello,

Here is an authentication link to log in to your course(s):

http://grader.cs.uml.edu/main/auth?email=fgmartin13%40gmail.com&key= [REDACTED]

Have fun!
--
The Bottlenose Web App
```

**Comment by fgmart-zz** [comment]
@marksherman re: server used to redirect http to https, OK, but the redirect isn't working now, so if you click on a link that you receive, presently it 404s.

Probably the right way to fix this is to have BN generate a URL with an https.

**Comment by marksherman** [comment]
The root_url variable needs to be changed to https. Recommend escalating to HIGH IMPORTANCE as this same variable is used throughout the application.

**Comment by marksherman** [comment]
Alternatively, the grader server could deploy the same https redirect onto itself. I'm looking into that now.

**Comment by fgmart-zz** [comment]
I'd rather this were fixed w/o the redirect.

It would also save users time -- 0.5 sec per redirect x 120 users x 100
clicks per semester = 6000 person-seconds saved this spring.

Fred

On Sun, Jan 11, 2015 at 3:43 PM, Mark Sherman notifications@github.com
wrote:

> Alternatively, the grader server could deploy the same https redirect onto
> itself. I'm looking into that now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_NatTuck_bottlenose_issues_102-23issuecomment-2D69510482&d=AwMCaQ&c=TqceLeU8_c9CVUat-eLTFu19-lyGiWSvB_skZXlxt8Q&r=18cCOnjUNVJkR7XAgiboog&m=G5RwlcGEpvL5DABWsqfHE6siPcQkm8GiJNsb8FBPzZc&s=f4GkqWiIb8Wd2QGHPFsl2SbvAzsJelDFYZYYRovr1pk&e=
> .

## 

Work Ready Life Ready World Ready

Director, Engaging Computing Group http://www.cs.uml.edu/ecg
Associate Professor, Computer Science http://blog.uml.edu/cs
Director of Student Success, College of Sciences
http://blog.uml.edu/science
University of Massachusetts Lowell, 1 University Avenue, Lowell MA 01854
p: 978/934–1964 f: 978/934–2705 email: fredm@cs.uml.edu

**Comment by NatTuck** [comment]
Give that a try.

**Comment by fgmart-zz** [comment]
Looking good!
