### ISSUE TITLE
some pages show UTC, some EST time

### ISSUE THREAD

**Issue by marksherman** [NatTuck/bottlenose-classic#114]
https://grader.cs.uml.edu/registrations/###/submissions_for_assignment/### shows date in UTC
2015-01-24 17:28:49 UTC

while 
https://grader.cs.uml.edu/submissions/#### shows date in local EST
Sat Jan 24 2015 12:28:49 GMT-0500 (EST)

Makes me wonder what date is actually shown in the various list views of assignments and submissions.
I would prefer all show my EST locale. 

Maybe this is related to #113 ?

**Comment by NatTuck** [comment]
Bottlenose stores dates internally in UTC and then translates them to local time client-side in JavaScript. The javascript is probably just missing.
