### ISSUE TITLE
Points values above 100% show check-minus sign

### ISSUE THREAD

**Issue by marksherman** [NatTuck/bottlenose-classic#121]
Easy fix: Should continue to show full-points check mark

Super fix: add a check-plus sign for above 100% 

it is possible for hand-grading to assign values above the given denominator, and this is often done intentionally. The icon does not accurately reflect these cases. 

example: https://grader.cs.uml.edu/registrations/559/submissions_for_assignment/421

**Comment by NatTuck** [comment]
Duplicate of #127
