### ISSUE TITLE
Late penalty not properly enforced

### ISSUE THREAD

**Issue by NatTuck** [NatTuck/bottlenose-classic#15]
Sarita was having trouble with late penalties not being properly applied for her assignments.

**Comment by NatTuck** [comment]
Still don't have an example for this.

**Comment by derrell** [comment]
I can't figure out how it works. The text says that the assignment must be turned in _before_ this date, but it seems not to mean that. I think it means _by no later than this date_ but I've had some cases where it deducted late penalties even when on that date. Can you clarify what it is implemented to do?

**Comment by NatTuck** [comment]
Apparently you're right.

What's implemented is "no later than this date". I'll update the text to reflect that, since that's what everyone probably wants anyway. Let me know if you can come up with an example where that's not what's happening.
