### ISSUE TITLE
One more icon: submitted, but not zero and not perfect

### ISSUE THREAD

**Issue by derrell** [NatTuck/bottlenose-classic#18]
As a warning to the teacher when entering teacher scores, it would be useful if the icon for "not all automatic tests passed" were something obviously different than the green check. My manual reviews of their paper printouts allow me to determine a score, but if I miss something that was detected by the automatic tests, I'd like to be more obviously notified of it than just an automatic score that isn't the full value.

**Comment by NatTuck** [comment]
Fixed in 916b25f6ec
