### ISSUE TITLE
Bulk-entry of grades fails when no student submission

### ISSUE THREAD

**Issue by derrell** [NatTuck/bottlenose-classic#23]
See #17. The solution works great when the student has submitted, but does appears to, but does not actually store the score, if the student has not submitted. This prevents using this feature for bulk-entry of scores on an assignment that does not require student submission.

**Comment by NatTuck** [comment]
The following procedure works for me locally:
- Create a new assignment.
- Enter scores for each student on the assignment page, clicking "Create Submission" for each one.
- View the saved scores on the CSV dump for the course.

Where do you run into trouble?

**Comment by derrell** [comment]
It fails attempting to enter a score for a student, where most people have submitted, but the students who have not do not have their grades saved. It appears to save, but upon refresh, it has not saved.

I'm also just now finding that scores I'm 90% certain I entered yesterday have gone missing...

**Comment by derrell** [comment]
It is working, on my current assignment, to save a score for a student who has not submitted. I'll try again with the other assignment.

**Comment by derrell** [comment]
It's working now, but multiple attempts earkuerm in the assignment I'm now back to, did not work. I'm also quite convinced that some grades I entered yesterday (or a couple of days ago) are now gone. I'll find out when the students see their zero, and show me the printout I gave back to them today.

**Comment by derrell** [comment]
I'm seeing that on occasion, when I press Enter after entering a teacher score, the score does not update. I have to press Enter yet again, and then the page refreshes after having saved the score. This happens about 5% of the time, it seems. Now that I'm watching for it, I can see how scores from a couple of days ago could have gone away. They might not have ever been saved, even though I entered them and pressed Enter.

**Comment by NatTuck** [comment]
I'm pretty sure this is fixed. Let me know if you can get it to happen still.

**Comment by derrell** [comment]
I ran through the same procedure a couple of times yesterday, entering a whole set of grades on an assignment that had no student submission, and did not encounter the problem I'd seen previously. I'll let you know if I catch it in the act of failing again. Thanks.
