### ISSUE TITLE
Rewrite YouTube embed links to allow rel=0 to work

### ISSUE THREAD

**Issue by fgmart-zz** [NatTuck/bottlenose-classic#29]
E.g., rewrite

http://www.youtube.com/embed/eVN83Drd2J0

to

http://www.youtube.com/v/eVN83Drd2J0&rel=0

**Comment by NatTuck** [comment]
Rewriting links like this doesn't seem to work with the HTML5 video player. This would break the site for some browsers and devices, including my primary development machine.

**Comment by fgmart-zz** [comment]
So the videos I posted in the Intro to Haskell section don't show up for you?

**Comment by NatTuck** [comment]
Yea. I just get a black rectangle and no video.

It's debatable whether anyone else in the world has a desktop computer set up for HTML5-youtube only, but I think it's pretty common on tablets.

**Comment by fgmart-zz** [comment]
Is there another way to solve it?

**Comment by NatTuck** [comment]
Nothing obvious. I'll have to look at the problem a bit more.
