### ISSUE TITLE
allow guests RO access to courses

### ISSUE THREAD

**Issue by fgmart-zz** [NatTuck/bottlenose-classic#35]
Guests should have read-only access to the site.

**Comment by NatTuck** [comment]
This conflicts with the behavior that Mark / Derrell / Sarita want for their grading system. I'll have to think about how to most easily support both use cases.

**Comment by marksherman** [comment]
Have individual courses have a property for "public read-only", the computing I courses would remain "off". ?

**Comment by fgmart-zz** [comment]
So, with the big BN update, r/o access to course materials is now blocked.

I'd really like it allowed again.

**Comment by NatTuck** [comment]
Removed guest user access. (breaks #35)

**Comment by marksherman** [comment]
Can a guest have an account, so they can get RO per-course priv?

**Comment by NatTuck** [comment]
I'll have to figure out how to show in the UI, but I'll re-enable read-only access to marked-public courses for people who have BN accounts but are not registered for that course.

I was hoping that with lessons gone nobody would notice if I removed this feature, but apparently not.

**Comment by NatTuck** [comment]
I removed guests. Currently anyone who wants to see BN content needs to
register.

At the moment there are only two permission levels on the course:
- Student
- Teacher

If you want to offer a single student access to a course, it's probably
easiest to add them as a student but exclude them from reports. Then they
can even try the assignments.

Fred - What's your use case on public access to courses? Should they be
indexed by Google?

**Comment by NatTuck** [comment]
I've added a checkbox to publish assignments, and a public view for courses. That work, @fgmart ?
