### ISSUE TITLE
"wait-mark" graphic is unclear

### ISSUE THREAD

**Issue by marksherman** [NatTuck/bottlenose-classic#40]
The "wait-mark.gif" graphic of the spinning clock appears most commonly when a program fails to compile. The image gives the impression that something is still processing, which it is not. After an unsuccessful compile the display should the red X or some other indication with a certain meaning.

**Comment by derrell** [comment]
It happens equally frequently when (a) the program crashes while running, and (b) the program enters an infinite loop.

**Comment by marksherman** [comment]
All of which, I believe, count under the same conditions of "it has in fact
ended" for which the spinner is no longer appropriate.

**Comment by NatTuck** [comment]
Now shows crash icon after 10 minutes.
