### ISSUE TITLE
Document the test format

### ISSUE THREAD

**Issue by derrell** [NatTuck/bottlenose-classic#42]
e.g.,
- What does it mean when the test.t issues /say "1..5"/ ? It doesn't affect the actual number of tests that are run. How is it used?
- I would like for some tests to be "fatal", i.e., if those tests are not passed, then further tests should not be run. Is it reasonable to simply exit from the test at that point?
- I would like for some tests to be "worth" more than others, as far as the point deduction. Some tests are for fairly trivial issues, while others test significant functionality of the application. How can I cause some tests to have different value than others?

**Comment by marksherman** [comment]
I can speak to point 1, the /say "1..5"/
That declares to TAP how many test results to expect. The number of points
delivered will be divided by the second number that's said there. If you
say 1..5, full points will be awarded when it sees 5 instances of "ok
$testnum". If you only run three tests, but declare 5, and all tests pass,
you'll still only get 3/5ths of the points.

Not sure how it works if you're off in the other direction, where you do
more tests than you declared.

If you don't run tests, it counts as a fail, so making fatal tests is as
simple as skipping the rest in your test code.

For worth more, in my current understanding, it's not possible. I have to
toss that one over to Nat.

**Comment by NatTuck** [comment]
Here's the best spec for the Test Anything Protocal:
http://search.cpan.org/~petdance/Test-Harness-2.64/lib/Test/Harness/TAP.pod

Bottlenose doesn't fully support it (e.g., comments), but that's a bug.

Tests having different point values is kind of a semantic mismatch, but exactly what the description text is for tests is undefined so we can put extra point values there I guess.

**Comment by NatTuck** [comment]
Take a look at test/fixtures/files/HelloWorld-single-grading.tar.gz for an example of a test with modified point values.
