### ISSUE TITLE
Request: tgz compatibility

### ISSUE THREAD

**Issue by marksherman** [NatTuck/bottlenose-classic#45]
Request to identify submissions that end with .tgz as well as .tar.gz as archive files, and expand them.

I thought that it checked the filename for /gz$/, but it's actually checking for /\.gz$/

This tweak would add compatibility for the less-canonical, but equally valid .tgz extension, which happens sometimes. The two suffixes are often considered interchangeable, and there's no reason to question that on a system that deals with amateurs.

**Comment by derrell** [comment]
It's a good thing this request came through now. I am putting together an assignment that will have a tarball for the Assignment file, and, as I almost always do, I would certainly have produced a .tgz file. Yes, .tgz and .tar.gz are generally considered equivalent.

**Comment by derrell** [comment]
Hmmm... The system has always taken .tgz files for the Grading file...???

**Comment by marksherman** [comment]
Correct. Not an issue for the goading file.

**Comment by NatTuck** [comment]
As long as you aren't letting your students submit Makefiles with a lowercase "m"...
