### ISSUE TITLE
Ability to download tarball of submissions

### ISSUE THREAD

**Issue by derrell** [NatTuck/bottlenose-classic#47]
Pending (or even after) completion of #44, it would be extremely useful to be able to generate a downloadable tarball of (at the instructions option) all submissions for a course, or all submissions for a specific assignment.

**Comment by marksherman** [comment]
I've been thinking over how to do a live diff on the site between attempts at a single problem. Similar, idea, I think.

**Comment by NatTuck** [comment]
Mulhern also votes for downloading a tarball of submissions for an assignment.

**Comment by NatTuck** [comment]
Merged #128
