### ISSUE TITLE
Chapter view should show Assignment due dates

### ISSUE THREAD

**Issue by fgmart-zz** [NatTuck/bottlenose-classic#49]
It would be good to provide students with an overview of when stuff is due.

E.g., the "Building an Interpreter" chapter at https://grader.cs.uml.edu/chapters/29 has three Assignments.

Each is due different days.  It would good if they could see this at the Chapter overview.

**Comment by NatTuck** [comment]
Added in commit 33d1edb98e5bd27623b77c4b7d9f0f61b8116f45
