### ISSUE TITLE
Assignments denominator different for some students

### ISSUE THREAD

**Issue by marksherman** [NatTuck/bottlenose-classic#57]
On the course page, the column "assignments" for each student lists score/max, 0/max, or 0/0. There is no immediately obvious pattern as to why.

Example: https://grader.cs.uml.edu/courses/10

**Comment by NatTuck** [comment]
Assignment summaries are cached for performance. The cache isn't cleared properly when new assignments are added. I need to carefully resist adding a "rebuild cache" button.

**Comment by NatTuck** [comment]
Should be fixed in 3c96ad2d69 ; the cached scores will still lag new and updated questions and assignments by a minute or two.
