### ISSUE TITLE
While editing assignment, number field (due date) does not update all the time

### ISSUE THREAD

**Issue by marksherman** [NatTuck/bottlenose-classic#6]
If you update the due date (day of the month), and immediately click "update assignment" button, it does not save with the change.

You must first tab or click out of the day-of-the-month field, then click "update". Quirky.

**Comment by NatTuck** [comment]
Works for me.

**Comment by marksherman** [comment]
I've recreated it. It's not a selection focus issue. If you type in a number, and it presents you an option, you need to acknowledge the option for it to up date, either by: clicking the option in the drop-down, collapsing the drop-down, or clicking off to change focus.

If you select the item from the dropdown list, instead of/in addition to typing, it never fails.

**Comment by NatTuck** [comment]
Hmm... apparently this is a real bug and also my fault. I pushed a fix replacing stock date pickers with JqueryUI widgets.

**Comment by marksherman** [comment]
You are a gentleman of a developer. Don't let anyone tell you otherwise.
