### ISSUE TITLE
Random features from Fred

### ISSUE THREAD

**Issue by NatTuck** [NatTuck/bottlenose-classic#63]
easy?
- make it so when you approve a student, they default to being Yes in Show in Reports (this will save time)
- display students' email addrs below name in main view (so I can tell students what email addr they're using)

a bit of work?
- batch upload of name / email CSVs.  This one really matters, not just to save me time manually approving, but more importantly so students don't have to wait for me to approve their accounts.

**Comment by fgmart-zz** [comment]
The display student emails thing is done :)

**Comment by NatTuck** [comment]
Should all be implemented.
