### ISSUE TITLE
Difficult to know if Teacher grade has been entered

### ISSUE THREAD

**Issue by derrell** [NatTuck/bottlenose-classic#7]
On the student status report, there is no way to see whether the indicated grades are solely Bottlenose-generated, or whether the Teacher grade has been taken into account. It appears, immediately after submitting a number of working programs, that full credit has been received, even though the programs do not meet other teacher-instituted requirements.

**Comment by NatTuck** [comment]
The new "hide grading" setting for assignments eliminates this problem unless a student submits late work after grading is complete.
