### ISSUE TITLE
a merged field with automatic score and teacher score

### ISSUE THREAD

**Issue by fgmart-zz** [NatTuck/bottlenose-classic#79]
it's a pain to deal with the grades-download CSV when some student have only an automatic score for an assignment, and others have had that score replaced by a teacher score.

there should be a generated field, simply "score," which is:
- the automatic score, if the teacher score is blank
- the teacher score, if it's filled in.

This is pretty important....

**Comment by NatTuck** [comment]
In addition to the "effective score" field?

**Comment by fgmart-zz** [comment]
yes... just like effective score :+1:
