### ISSUE TITLE
Suspension for teacher grading results to student

### ISSUE THREAD

**Issue by derrell** [NatTuck/bottlenose-classic#9]
I would like to be able to prevent all teacher grading from being presented to the student until all grading of an assignment is complete, or until otherwise released to the student. In particular and especially, I would like to have the option to read over the grader's comments and assigned grade before that is presented to the student. I'd also like for all students to have access to their teacher grade at the same time.

**Comment by NatTuck** [comment]
With my latest commit, there is now a checkbox in Edit Assignment called "hide grading" that hides teacher scores, final scores, and teacher notes from all students for that assignment. Your workflow is probably to check the box for new assignments and then uncheck it only once grading is finished.
