### ISSUE TITLE
bulk-add > paste list of email doesn't seem to generate email to student

### ISSUE THREAD

**Issue by fgmart-zz** [NatTuck/bottlenose-classic#95]
i'm testing on my own email addrs...

**Comment by fgmart-zz** [comment]
similarly for CSV upload.

**Comment by fgmart-zz** [comment]
actually just manually asking for auth link to be resent, from top level UI, fails.

**Comment by NatTuck** [comment]
Should work now. Was an email configuration issue on grader.cs.
