### ISSUE TITLE
serious authentication bug?

### ISSUE THREAD

**Issue by fgmart-zz** [NatTuck/bottlenose-classic#97]
My fgmartin13@gmail.com user seems to be able to view all courses in the system, even though it's only enrolled for a subset of them.

Here's that user's view of https://grader.cs.uml.edu/courses:

![bn-your-courses](https://cloud.githubusercontent.com/assets/1038856/5603170/9460b132-9344-11e4-81e5-a3b5685c95fc.png)

But, if I log in as fredm@cs.uml.edu and examine the fgmartin13 user, this is what he's enrolled in:

![fgmart](https://cloud.githubusercontent.com/assets/1038856/5603175/ca365f00-9344-11e4-9516-5cfa7f1a1770.png)

**Comment by fgmart-zz** [comment]
Whoops I realized this is a feature, not a bug... you're deliberately revealing all courses to the user.

However, there is still an issue. I had added fgmartin13@gmail.com to the new 91.204.201 course, and it didn't get added to his courses.

See instructor's view:

![fgmart-204](https://cloud.githubusercontent.com/assets/1038856/5603184/3f0228c8-9345-11e4-948b-068c173e5a8d.png)

**Comment by fgmart-zz** [comment]
Also, I notice that fgmartin13@gmail.com is display as realname "Fred G Martin" in one place, and "Fred Martin" in another... can that be related?

**Comment by NatTuck** [comment]
Huh. Looks like it's possible to add duplicate users with the same email. That shouldn't happen.

**Comment by NatTuck** [comment]
Are messages ending up in your Spam box?

**Comment by NatTuck** [comment]
Nice. One user is " fgmartin13@gmail.com". Looks like I have to sanitize input better.

**Comment by NatTuck** [comment]
Looks like an email misconfiguration problem on the server. Should work now.

**Comment by NatTuck** [comment]
Or not...

**Comment by NatTuck** [comment]
Nope, just forgot to restart the server. Should work now.
